version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements/dev"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    target-branch: "production"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "production"
