name: "Audit"

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  audit:
    name: "Audit"
    runs-on: ${{ matrix.version.runner }}
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        version: [
          { pyds: "1.0", runner: "ubuntu-20.04" },
          { pyds: "1.0.2", runner: "ubuntu-20.04" },
          { pyds: "1.0.3", runner: "ubuntu-20.04" },
        ]
    env:
      WORKING_DIR: versions/${{ matrix.version.pyds }}
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0

      - name: Install python
        uses: actions/setup-python@v7.0.0
        with:
          python-version-file: ${{ env.WORKING_DIR }}/.python-version

      - name: Audit
        run: |
          uv audit --output-format sarif > uv-audit.sarif

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4.38.2
        with:
          sarif_file: ${{ env.WORKING_DIR }}/uv-audit.sarif
          category: uv-audit
