name: "Publish"

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Upload to TestPyPi'
        required: true
        default: false
        type: boolean

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Production cannot be published
        run: exit 1
