name: "Publishing"
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to publish'
        required: true
        default: 'production'
        type: string
      test:
        description: 'Upload to TestPyPi'
        required: true
        default: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/setup-python@v6.0.0
        with:
          check-latest: 'true'
          cache: 'pip'

      - name: Publishing tool installation
        run: python3 -m pip install twine

      - name: Build package
        run: python3 -m build

      - name: Upload package to PyPi
        if: github.event.inputs.test == false
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python3 -m twine upload dist/*

      - name: Upload package to TestPyPi
        if: github.event.inputs.test == true
        env:
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
        run: python3 -m twine upload --repository testpypi dist/*
